[programs.localnet]
counter = "9b1LijhFmtMDfQAuq9aRVqRiFLeG6Edm5JGiDHZu3AUM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/abhi3700/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
